urls.py
from django.conf import settings
from django.urls import path
from .views import views

app_name = 'BBlog'
urlpatterns = [

    path('articles/', views.articleListView, name="articles"),
    path('<slug:slug>/', views.articleView, name='article'),
]

models/article.py
############################################################
############################################################

##     model name: Article                    
##     superclass: Models
##     subclass:   
##     points to: Container
##     abstract: No

##     description: 
"""
it contains an article, a series of images and text. 
it is an extension of the base.html
it refer to a general topic so it can be filtered.
"""

##     parameters:
#           author
#           date_created
#           date_updated
#           url 
#           title
#           paragraphs         

##       methods:
#           __str__
#           orderedContent

####    Admin stuff

##    fixed CSS-Flex parameters:


##    ignored in admin param:


############################################################
############################################################
from django.db import models
from .categories import *
from django_quill.fields import QuillField

class Article(models.Model):


    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    # Meta
    author = models.CharField(
        max_length=10,
        blank=True,
        null=True,
    )
    date_created = models.DateTimeField(
        auto_now_add=True, 
        editable=False,
        )
    date_updated = models.DateTimeField(
        auto_now=True,
        )

    topic = models.ForeignKey(
        Topic, models.SET_NULL, blank=True, null=True
    )
    sub_topic = models.ForeignKey(
        Subtopic, models.SET_NULL, blank=True, null=True
    )
    category = models.ForeignKey(
        Category, models.SET_NULL, blank=True, null=True
    )
    sub_category = models.ForeignKey(
        Subcategory, models.SET_NULL, blank=True, null=True
    )
    argument = models.ForeignKey(
        Argument, models.SET_NULL, blank=True, null=True
    )
    
    # every page is pointed by an url that must be set 
    # in the url patterns when the object is saved
    # the url setted is:
    slug = models.SlugField(
        max_length=120,
        blank=True,
        null=True,
    )
    title = models.CharField(
        max_length=100,
        blank=True,
        null=True,
    )
    paragraphs = QuillField(default=None)
       
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    
    def __str__(self):
        return self.title

models/categories.py
############################################################
############################################################

##     model name: Categories                    
##     superclass: Models
##     subclass:   
##     points to: 
##     abstract: No

##     description: 
"""
it contains a cateogrie of articles
"""

##     parameters:
#           category        

##       methods:
#           __str__
#           

####    Admin stuff

##    fixed CSS-Flex parameters:


##    ignored in admin param:


############################################################
############################################################
from django.db import models

class Topic(models.Model):
    topic = models.CharField(
        max_length=40,
        blank=True,
        null=True,
    )
    
    def __str__(self):
        return self.topic


class Subtopic(models.Model):
    sub_topic = models.CharField(
        max_length=40,
        blank=True,
        null=True,
    )
    
    def __str__(self):
        return self.sub_topic


class Category(models.Model):
    category = models.CharField(
        max_length=40,
        blank=True,
        null=True,
    )
    class Meta:
        verbose_name_plural = "categories"
    
    def __str__(self):
        return self.category


class Subcategory(models.Model):
    sub_category = models.CharField(
        max_length=40,
        blank=True,
        null=True,
    )
    class Meta:
        verbose_name_plural = "sub_categories"
    
    def __str__(self):
        return self.sub_category


class Argument(models.Model):
    argument = models.CharField(
        max_length=40,
        blank=True,
        null=True,
    )
    
    def __str__(self):
        return self.argument

forms.py
from django import forms
from .models.article import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = [
            'author', 
            'date_updated', 
            'topic', 
            'sub_topic', 
            'category', 
            'sub_category',
            'argument',
            'title',
            'paragraphs',
            'status',
            ]

views/views.py
from django.shortcuts import get_object_or_404, render
from ..models.article import Article


def articleListView(request):
    articles = Article.objects.filter(status="published")

    context = {
        'articles': articles,
    }     
    return render(request, 'BBlog/article_list.html', context)


def articleView(request, slug):
    article = get_object_or_404(Article, slug = slug) 
    
    context = {
        'article'  : article,       
        }

    return render(request, 'BBlog/article.html', context)

templates/BBlog/article.html
{% extends "website/base.html" %}
{% block content %} 
        <section class="container-fluid">
            <h1 class="h1 m-4 text-center">{{ article.title }}</h1>
            <div class="mx-4 px-5 d-flex flex-column flex-md-row justify-content-start">
                <span class ="px-3">author: {{ article.author }}</span>
                <span class ="px-3">created: {{ article.date_created }}</span>
                <span class ="px-3">updated: {{ article.date_updated }}</span>
            </div>
            <div class="h4 px-5 m-4">{{ article.topic }}</div>
            <div class="m-5 p-3">
                {{ article.paragraphs.html|safe }}
            </div>
        </section>
{% endblock %}  
        

templates/BBlog/article_list.html
{% extends "website/base.html" %}
{% block content %} 
        <h1 class="h1 m-5 text-center">Articles</h1>
        <ul class="list-group list-group-flush container-fluid mx-5 p-3">
        {% for article in articles %}
            
            <a href="{% url 'BBlog:article' slug=article.slug  %}" class="list-group-item list-group-item-action" aria-current="true">
                <h5 class="mb-1">{{ article.title }}</h5>
                <small>{{ article.date_created}}</small>
            </a>
        
        {% empty %}
            <li>No articles yet.</li>
        {% endfor %}
        </ul>
        
{% endblock %} 

templates/article.html
{% extends "base.html" %}
{% block content %} 
        <section class="container-fluid">
            <h1 class="h1 m-4 text-center">{{ article.title }}</h1>
            <div class="mx-4 px-5 d-flex flex-column flex-md-row justify-content-start">
                <span class ="px-3">author: {{ article.author }}</span>
                <span class ="px-3">created: {{ article.date_created }}</span>
                <span class ="px-3">updated: {{ article.date_updated }}</span>
            </div>
            <div class="h4 px-5 m-4">{{ article.topic }}</div>
            <div class="m-5 p-3">
                {{ article.paragraphs.html|safe }}
            </div>
        </section>
{% endblock %}  
        